apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: smarthome
      defaultBucket: smarthome
      httpMode: POST
    secureJsonData:
      token: smarthome-dev-token
    isDefault: true
